name: pre-commit

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Display build environment
        run: printenv

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.16' # The Go version to download (if necessary) and use.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
